### ISSUE TITLE
IndexError after load_weights

### ISSUE THREAD

**Issue by lupo112** [iliaschalkidis/ELMo-keras#3]
Hi

I am trying to load weight from `elmo_best_weights.hdf5` file and I am getting this error:
```py
Traceback (most recent call last):
  File ".../ELMo-keras/train_demo.py", line 93, in <module>
    elmo_model.evaluate(test_generator)
  File "...\ELMo-keras\elmo\model.py", line 225, in evaluate
    print('Forward Langauge Model Perplexity: {}'.format(ELMo.perplexity(y_pred_forward, y_true_forward)))
  File "...\ELMo-keras\elmo\model.py", line 297, in perplexity
    y_true_seq = to_categorical(y_true_seq, y_pred_seq.shape[-1])
  File "...\ELMo-keras\.venv\lib\site-packages\keras\utils\np_utils.py", line 34, in to_categorical
    categorical[np.arange(n), y] = 1
IndexError: index 22246 is out of bounds for axis 1 with size 200
```

In `model.py` was added method `load_weights`:
```py
    def load_weights(self):
        self._model.load_weights(os.path.join(MODELS_DIR, 'elmo_best_weights.hdf5'))
```

And my `train_demo.py` looks like this:
```py
parameters = # ... unchaged

# Set-up Generators
# ... unchanged

# Compile ELMo
elmo_model = ELMo(parameters)
elmo_model.compile_elmo(print_summary=True)

elmo_model.load_weights()

# Evaluate Bidirectional Language Model
elmo_model.evaluate(test_generator)

# Build ELMo meta-model to deploy for production and persist in disk
elmo_model.wrap_multi_elmo_encoder(print_summary=True, save=True)
```

Any idea how to get this work or where can be the problem?

**Comment by iliaschalkidis** [comment]
@lupo112 did you find a workaround and you closed the issue? Please let me know if I need to fix something...

**Comment by lupo112** [comment]
Hi, I found a bug in my code. The `load_weights` method did not use similar settings as `save` method.

Please see my attached solution:
```py
# changed in model.py

def load_weights(self, sampled_softmax=True):
    if not sampled_softmax:
        self.parameters['num_sampled'] = self.parameters['vocab_size']
    self.compile_elmo()
    self._model.load_weights(os.path.join(MODELS_DIR, 'elmo_best_weights.hdf5'))
```
